/*
 * Find the Difference (Easy)
 * 
 * Given two strings s and t which consist of only lowercase letters.
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * Find the letter that was added in t.
 * 
 * Input: s = "abcd" t = "abcde"; Output: e
 */

/*
 * 思路：
 * 1.类比Single Number那道题，两个输入字符数组加起来就等于除一个词出现奇数次，其余出现偶数次，边界情况已被cover，时间复杂度O(n+m)
 * 2.利用HashMap，建立26个字母对于出现次数的映射，遍历s，出现一次则次数+1；遍历t，出现一次次数-1，若修改次数后<0，则找到。时间复杂度最差O(n+m)
 * 3.类比思路1，首先累加t的字符，再依次减去s的字符即是最后的结果，时间复杂度O(n+m)
 */
public class question389 {
	public char findTheDifference(String s, String t) {
        char[] s_array = s.toCharArray();
        char[] t_array = t.toCharArray();
        
        char ans = 0;
        for(int i=0; i<(s.length()+t.length()); i++) {
            if(i < s.length()) {
                ans ^= s.charAt(i);
            }
            else {
                ans ^= t.charAt(i-s.length());
            }
        }
        return ans;
    }
}
